import { Inter } from "next/font/google";
import Header from "./header";
import Footer from "./footer";
import Timkiem from "./timkiem/page";
import "./globals.css";
import Providers from '../redux/Provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
    <html lang="en">
      <head>
      <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="images/fevicon/fevicon.png" type="image/gif" />
        <title>HandTime</title>
        <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet" />
        <link href="css/font-awesome.min.css" rel="stylesheet" />
        <link href="css/style.css" rel="stylesheet" />
        <link href="css/responsive.css" rel="stylesheet" />
      </head>
      
      <body className={inter.className}>
      <Header/>
        {children}
        <Footer/>
        </body>
       
        <script type="text/javascript" src="/js/jquery-3.4.1.min.js"></script>
   
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
   
  <script type="text/javascript" src="/js/bootstrap.js"></script>
   
  <script type="text/javascript" src="/js/custom.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
    </html>
    </Providers>
  );
}
